[project]
name = "simple-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "mcp==1.9.4",
    "pandas>=2.3.0",
    "pyarrow>=20.0.0",
    "pyimagej==1.7.0",
]
